name: PPO-minigame
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - "numpy<2.0"
  - cpuonly
  - pytorch=2.2
  - pip:
    - stable-baselines3==2.3.0
    - pysc2==3.0.0
    - gymnasium==0.29.1
    - tensorboard
    - opencv-python>=4.8.0
    - absl-py>=1.0.0
    - "protobuf>=3.20,<4.0"
    - pyyaml>=6.0
