name: minigame
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy<2.0
  - cpuonly
  - pytorch=2.2
  - torchvision=0.17
  - torchaudio=2.2
  - gymnasium=0.29
  - matplotlib
  - tensorboard
  - opencv
  - absl-py
  - protobuf>=3.20,<4.0
  - pyyaml
  - pip:
    - stable-baselines3==2.3.0
    - sb3-contrib==2.3.0
    - pysc2==3.0.0
